using Dalleni.Domin.Enums;

namespace Dalleni.Application.DTOs.Responses.Notifications
{
    /// <summary>
    /// Represents a notification returned to the client.
    /// </summary>
    public class NotificationResponseDto
    {
        /// <summary>
        /// The unique identifier of the notification.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// The user who generated the notification.
        /// Null when the notification was generated by the system.
        /// </summary>
        public Guid? ActorId { get; set; }

        /// <summary>
        /// Title of The Notifications
        /// </summary>
        public string Title { get; set; } = null!;
        /// <summary>
        /// The Notification Content
        /// </summary>

        public string Message { get; set; } = null!;


        /// <summary>
        /// The type of notification.
        /// </summary>
        public NotificationType Type { get; set; }

        /// <summary>
        /// The type of entity associated with the notification.
        /// </summary>
        public NotificationEntityType EntityType { get; set; }

        /// <summary>
        /// The identifier of the entity associated with the notification.
        /// </summary>
        public Guid? EntityId { get; set; }


        /// <summary>
        /// Indicates whether the notification has been read.
        /// </summary>
        public bool IsRead { get; set; }

        /// <summary>
        /// The time at which the notification was created.
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// The time at which the notification was read.
        /// </summary>
        public DateTime? ReadAt { get; set; }
    }
}